name: GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload site from /root
        uses: actions/upload-pages-artifact@v4
        with:
          path: root
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
